id: P009496
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:25.264691
source_metadata:
  id: bdr:W29905
  title: དམ་ཆོས་པད་དཀར་དང་བསྟན་འཛིན་དོན་འགྲུབ་སོགས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    afb6df4fef3c4e968089f770431ff8b8:
      image_group_id: I5670
      title: ''
      volume_number: 1
      total_pages: 628
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
