id: IF113E4F4
legacy_id: P009496
ocr_import_info:
  bdrc_scan_id: W29905
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T10:53:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:42:15.343689+00:00'
last_modified: 2022-09-02 22:43:14.781128
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29905
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29905
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་པད་དཀར་དང་བསྟན་འཛིན་དོན་འགྲུབ་སོགས་ཀྱི་རྣམ་ཐར།
statistics:
  ocr_word_mean_confidence_index: 0.742399052129393
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I5670:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5670
      total_pages: 628
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5670.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.742399052129393
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
