id: IF113E4F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:57:18+00:00'
last_modified: '2022-06-08T11:26:45.450480+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29905
  title: དམ་ཆོས་པད་དཀར་དང་བསྟན་འཛིན་དོན་འགྲུབ་སོགས་ཀྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E77E:
      image_group_id: I5670
      title: ''
      total_pages: 628
      order: 1
      base_file: E77E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
